# Generated by Django 2.0.7 on 2020-05-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyrc_certi',
            name='email',
        ),
    ]
